project:
  type: website
  output-dir: docs

author: "Pablo Salazar-Mendez"

website:
  title: "Pablo Salazar-Mendez"
  image: "https://quarto.org/quarto.png"
  description: "Personal academic website of Pablo Salazar-Mendez, Genomic sciences undergraduate student"

  navbar:
    background: dark
    left:
      - text: About
        menu:
          - text: News
            href: posts.qmd#category=news
          - text: Events
            href: posts.qmd#category=event
          - text: Contact
            href: contact.qmd
      - text: Research
        menu:
          - text: List of Publications
            href: publications.qmd
          - text: Selected Papers
            href: posts.qmd#category=paper
          - text: Grants
            href: projects.qmd
      - text: Teaching
        href: teaching.qmd
      - text: Outreach
        menu:
          - text: Presentations
            href: posts.qmd#category=presentation

    right:
      - text: CV
        href: https://docs.google.com/document/d/1jicPtkpFpaje2KxcX6Q22p1kb-Ui2l33lbsNbGqBdqQ/export?format=pdf
        target: _blank
      - icon: github
        href: https://github.com/pablomics-004/pablomics-004.github.io
        target: _blank
      - text: "{{< fa brands bluesky >}}"
        href: https://bsky.app
        target: _blank
      - icon: rss
        href: posts.xml
        target: _blank

  page-navigation: true
  
  page-footer: 
    left: "[Pablo Salazar-Mendez](https://github.com/pablomics-004) &copy; <script>document.write(new Date().getFullYear())</script>" 
    center: "Build on [Quart Academic Website Template](https://github.com/drganghe/quarto-academic-website-template) adapted by [Dr. Gang He](http://drganghe.github.io)"
    right:  
      - icon: github
        href: https://github.com/pablomics-004/pablomics-004.github.io
        target: _blank
      - text: "{{< fa brands bluesky >}}" 
        href: https://bsky.app
        target: _blank
      - icon: rss
        href: posts.xml
        target: _blank  
  
  search:
    location: navbar
    type: textbox
  
  reader-mode: true

  draft-mode: unlinked
  
  repo-url: https://github.com/drganghe/quarto-academic-website-template
#  repo-actions: [edit, issue, source]
  
  open-graph: true
  
  twitter-card: true 
#  card-style: summary      
  
  site-url: "https://pablomics-004.github.io"
  
  google-analytics:
    tracking-id: ""  # Please delete or replace with your own tracking ID
    anonymize-ip: true 

bibliography: references.bib  # Add references.bib to the root folder to enable the bibliography function

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    title-block-banner: false
    include-in-header: "files/includes/_academic.qmd"

